### ISSUE TITLE
Remove best practices now merged into the spec

### ISSUE THREAD

**Issue by emmambd** [MobilityData/GTFS_Schedule_Best-Practices#57]
[A vote to merge specific best practices into the spec has passed](https://github.com/google/transit/pull/386). The duplicates should be removed from this repo now.

**Comment by isabelle-dr** [comment]
The scope for this issue is to remove the Best Practices that will become covered by the spec if the vote passes, correct?

**Comment by emmambd** [comment]
The goal of this issue is to flag for anyone who might only be paying attention to https://github.com/MobilityData/GTFS_Schedule_Best-Practices to go to https://github.com/google/transit/pull/386

I'll update this issue if the vote passes so it focuses on removing the best practices covered by spec.
